# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Message:
  fields:
    default: title, content
    form: title, content
  order_by: 
  relationships: 
  filters: created_at
  search: title
  application: typus_test_app

User:
  fields:
    default: email, remember_token, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip
    form: email, reset_password_token, remember_token, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip
  order_by: 
  relationships: 
  filters: created_at
  search: 
  application: typus_test_app

